# Generated by Django 3.1.6 on 2021-02-12 19:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(default=datetime.datetime(2021, 2, 12, 23, 45, 47, 385301))),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_bought', models.DateTimeField(default=datetime.datetime.now)),
                ('date_sold', models.DateTimeField(blank=True, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('merged', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('gain', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=16)),
                ('value', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('total_spent', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('sell_amount', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=16, null=True)),
                ('_purchase_price', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=16)),
                ('price_difference', models.FloatField(blank=True, default=0.0, max_length=24)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
