# Generated by Django 3.1.6 on 2021-03-09 15:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(default=datetime.datetime(2021, 3, 9, 15, 13, 31, 149025))),
                ('update_round', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('price_1h', models.FloatField(blank=True, default=0.0, max_length=24, null=True)),
                ('price_24h', models.FloatField(blank=True, default=0.0, max_length=24, null=True)),
                ('price_btc', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('price_eth', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_prices', models.TextField(blank=True, default='', null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_bought', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('date_sold', models.DateTimeField(blank=True, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('merged', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('gain', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=16)),
                ('value', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('total_spent', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('sell_amount', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=16, null=True)),
                ('_purchase_price', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=16, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=16)),
                ('price_difference', models.FloatField(blank=True, default=0.0, max_length=24)),
                ('total_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
