# Generated by Django 3.1.6 on 2021-02-13 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_auto_20210213_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 17, 55, 21, 489246)),
        ),
    ]
