# Generated by Django 3.1.6 on 2021-02-13 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20210213_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='date_bought',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='date',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 18, 6, 23, 874404)),
        ),
    ]
