# Generated by Django 3.1.6 on 2021-02-13 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20210213_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 18, 30, 0, 737125)),
        ),
    ]
