# Generated by Django 3.1.6 on 2021-02-14 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_auto_20210214_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 15, 11, 44, 205986)),
        ),
    ]
