# Generated by Django 3.1.6 on 2021-02-14 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_auto_20210214_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 19, 7, 54, 622233)),
        ),
    ]
