# Generated by Django 3.1.6 on 2021-02-15 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_auto_20210214_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price_1h',
            field=models.FloatField(blank=True, default=0.0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_24h',
            field=models.FloatField(blank=True, default=0.0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_btc',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_eth',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_1h',
            field=models.FloatField(blank=True, default=0.0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_24h',
            field=models.FloatField(blank=True, default=0.0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_btc',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_eth',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 7, 29, 16, 929315)),
        ),
    ]
