# Generated by Django 3.1.6 on 2021-02-15 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_auto_20210215_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='price_1h',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='price_24h',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='price_btc',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='price_eth',
        ),
        migrations.AddField(
            model_name='price',
            name='symbol',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 7, 57, 29, 443936)),
        ),
    ]
