# Generated by Django 3.1.6 on 2021-02-15 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_auto_20210215_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 9, 46, 24, 259734)),
        ),
    ]
