# Generated by Django 3.1.6 on 2021-02-16 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_auto_20210216_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='total_profit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='update_round',
            field=models.IntegerField(blank=True, default=0, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 16, 3, 50, 772495)),
        ),
    ]
