# Generated by Django 3.1.6 on 2021-02-16 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_auto_20210216_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 16, 4, 38, 550568)),
        ),
        migrations.AlterField(
            model_name='date',
            name='update_round',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
