# Generated by Django 3.1.6 on 2021-02-17 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0021_auto_20210217_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 14, 26, 18, 20093)),
        ),
    ]
