# Generated by Django 3.1.6 on 2021-02-17 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0022_auto_20210217_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 15, 21, 48, 505693)),
        ),
        migrations.AlterField(
            model_name='price',
            name='symbol',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
